### PR TITLE
[DNM] Tests base

### PR DESCRIPTION
**Pull request by Kampfkarren**
This is a basis for future tests on the codebase. It compares the output of TextReporter to ones in static files. Let me know if this is a good design before I proceed with basic tests.

### CODE REVIEW

**Comment by LPGhatguy** [comment]
I think any tests we run on our testing framework should be done within the context of Roblox, not outside Roblox like this.

I think we're also planning to effectively rebuild TestEZ from the ground up using a different technique (coroutine per test with a task monitor) while still being API compatible, and we'll be really mindful of testing when we're doing that.

**Comment by Kampfkarren** [comment]
> I think any tests we run on our testing framework should be done within the context of Roblox, not outside Roblox like this.
Would the better solution be instead of having a `.txt` file just be a `.lua` file that returns a string?

**Comment by LPGhatguy** [comment]
The solution is to not use files at all, at least until we have a compelling way to _write_ things back into the repository. No LuaFileSystem, no `os` method calls, purely dealing with Roblox instances.

**Comment by Kampfkarren** [comment]
Closing as per outside chat

**Pull request closed without merging**
